Move TravisLintBear.py to configfiles directory
coala/coala-bears pull request #2165
Opened 2017-12-14 07:09 UTC by anuyog1004

Closes https://github.com/coala/coala-bears/issues/1979

2017-12-14 10:29 UTC, prnvdixit requested changes
You might need to modify/move other files as well :smile:
eg. TravisLintBearTest.py & travislint_test_files (directory) should be in tests/configfiles now

2017-12-16 10:53 UTC, newbazz approved these changes
LGTM

2018-03-02 09:23 UTC, nj2237 approved these changes
Looks good to me

2018-04-21 23:42 UTC, jayvdb commented
See https://github.com/coala/coala-bears/issues/1979#issuecomment-383341608

2025-06-08 14:09 UTC, closed without merging