bears/python: Add RequirementsCheckBear
coala/coala-bears pull request #2935
Opened 2019-07-21 03:10 UTC by bkhanale

Closes https://github.com/coala/coala-bears/issues/1113

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

2019-07-28 14:00 UTC, sangamcse requested changes

2019-07-29 03:03 UTC, bkhanale commented on bears/python/requirements/RequirementsCheckBear.py
> +                         message=[s for s in lines if 'Could not' in s][0],
The exception will always have 'Could not' in it. Actually, the better solution was to just get `lines[0]` but, some of the warnings from pip are getting recorded too with it.

https://github.com/jazzband/pip-tools/blob/b37b91d251f7c7e590047f902e6f51e9a49d276c/piptools/exceptions.py#L22

2019-07-29 03:26 UTC, bkhanale commented on bears/python/requirements/RequirementsCheckBear.py
> +                         message=[s for s in lines if 'Could not' in s][0],
Updated, seems like a much better solution now.

2019-08-04 08:24 UTC, sangamcse approved these changes

2026-05-26 15:59 UTC, closed without merging